version: "3.9"
services:
  playwright-api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playwright.rule=Host(`playwright.strudel.marketing`)"
      - "traefik.http.routers.playwright.entrypoints=websecure"
      - "traefik.http.routers.playwright.tls.certresolver=letsencrypt"
      - "traefik.http.services.playwright.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true